services:
  db_postgres:
    image: postgres
    container_name: db_postgres_github_ci_cd
    restart: always
    ports: 
      - 1234:5432
    env_file:
      - .env
    volumes: 
      - postgres_github_ci_cd: /var/lib/postgres/data
    
  node_app_github_ci_cd:
    container_name: node_app_github_ci_cd
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_github_ci_cd
    env_file:
      - .env

volumes:
  postgres_github_ci_cd:

